#!/bin/bash
#
# Name the zip file and get md5
# GuunOS

. $ANDROID_BUILD_TOP/vendor/guun/tools/colors

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   MD5=md5sum
else
   MD5="md5 -r"
fi

# Determine build properties
MODVERSION=`grep ro.guun.version $OUT/system/build.prop | cut -d'=' -f2`
DEVICE=`grep ro.guun.device $OUT/system/build.prop | cut -d'=' -f2`
OTA_TYPE=`grep ro.guun.type $OUT/system/build.prop | cut -d'=' -f2`

GUUN_TARGET_PACKAGE=$MODVERSION-$DEVICE.zip
OUTFILE=$OUT/$GUUN_TARGET_PACKAGE

# Create OTA XML file
if [ -f $ANDROID_BUILD_TOP/ota_conf ]; then
cat >$OUT/ota_nougat_$DEVICE.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<XenonOTA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ota.xsd">
    <Stable>
        <$DEVICE>
            <Filename>$MODVERSION</Filename>
            <RomUrl
                id="rom"
                title="ROM"
                description="Download the latest build">https://mirrors.c0urier.net/android/teamhorizon/N/$OTA_TYPE/$DEVICE/$GUUN_TARGET_PACKAGE</RomUrl>
            <MD5Url
                id="md5"
                title="MD5"
                description="Download MD5 of the latest build">https://mirrors.c0urier.net/android/teamhorizon/N/$OTA_TYPE/$DEVICE/$GUUN_TARGET_PACKAGE.md5sum</MD5Url>
            <ChangelogUrl
                id="changelog"
                title="Changelog"
                description="View the latest changelog">https://mirrors.c0urier.net/android/teamhorizon/N/$OTA_TYPE/$DEVICE/Changelog.txt</ChangelogUrl>
            <OpenGappsUrl
                id="opengapps"
                title="Open Gapps"
                description="Download Open Gapps">http://opengapps.org</OpenGappsUrl>
            <ExtrasUrl
                id="extras"
                title="Extras"
                description="Download Extras">https://download.lineageos.org/extras</ExtrasUrl>
        </$DEVICE>
    </Stable>
</XenonOTA>
EOF
fi

# Create a md5 checksum image of the repacked package
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`
ln -f *-ota-*.zip $GUUN_TARGET_PACKAGE
rm *-ota-*.zip
$MD5 $img >$GUUN_TARGET_PACKAGE.md5sum
ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
echo -e ${cya}"===============-GuunOS Build Done-=============="${txtrst}
echo -e ${cya}"     _____                    ____   _____      "${txtrst}
echo -e ${cya}"    / ____|                  / __ \ / ____|     "${txtrst}
echo -e ${cya}"   | |  __ _   _ _   _ _ __ | |  | | (___       "${txtrst}
echo -e ${cya}"   | | |_ | | | | | | | '_ \| |  | |\___ \      "${txtrst}
echo -e ${cya}"   | |__| | |_| | |_| | | | | |__| |____) |     "${txtrst}
echo -e ${cya}"    \_____|\__,_|\__,_|_| |_|\____/|_____/      "${txtrst}
echo -e ${cya}"             Guun OS with Guun AI               "${txtrst}
echo -e ${cya}"------------------------------------------------"${txtrst}
echo -e ${cya}"Zip Name:"${cya}" $GUUN_TARGET_PACKAGE"${txtrst}
echo -e ${cya}"md5:"${cya}" $(cat $GUUN_TARGET_PACKAGE.md5sum | awk '{ print $1 }')"${txtrst}
echo -e ${cya}"size:"${cya}" $ZIPSIZE"${txtrst}
echo -e ${cya}"===============-GuunOS Build Done-=============="${txtrst}
)
